# Generated by Django 2.1.2 on 2018-10-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('genre', models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Comedy', 'Comedy')], default='Sci-Fi', max_length=100)),
            ],
        ),
    ]
