# Generated by Django 2.1.2 on 2018-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='overview',
            field=models.TextField(default='Overview default'),
            preserve_default=False,
        ),
    ]
