# Generated by Django 2.1.2 on 2018-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20181101_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review for Title1', max_length=128),
            preserve_default=False,
        ),
    ]
